spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MariaDB103Dialect
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/scouter_local?useMysqlMetadata=true
    username: root
    password: 1234
  sql:
    init:
      platform:
  servlet:
    multipart:
      location: /Users/ftpfile