spring:
  profiles:
    active: local
  banner:
    location: classpath:application/banner/banner.txt
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/scouter_local?useMysqlMetadata=true
    username: root
    password: 1234
    hikari:
      pool-name: Hikari
      minimum-idle: 5
      maximum-pool-size: 10
      max-lifetime: 60000
      idle-timeout: 10000
      autoCommit: false
      connection-init-sql: SET TIME_ZONE = '+09:00'
      connection-test-query: SELECT 1
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
    data:
      jpa:
        repositories:
          bootstrap-mode: deferred
  jpa:
    show-sql: true
    open-in-view: true
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: com.kite.scouter.global.CustomNamingStrategy
    generate-ddl: false
  main:
    allow-bean-definition-overriding: false
  web:
    resources:
      add-mappings: false
  flyway:
    baseline-on-migrate: true
    group: true
    baseline-version: 0.0.1
    enabled: true
    ignore-migration-patterns:
  servlet:
    multipart:
      max-file-size: 50MB
server:
  undertow:
    accesslog:
      enabled: true
  port: 8080
logging:
  file:
    path: /Documents/GitHub/logs
  level:
    org:
      springframework:
        web: debug
        http : debug
        security : debug
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace
      apache:
        tomcat: debug
    web: debug