CREATE TABLE IF NOT EXISTS CATEGORY (
    CATEGORY_ID BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CREATED_DT DATETIME(6) NOT NULL,
    MODIFIED_DT DATETIME(6) NULL,
    CATEGORY_NAME VARCHAR(50) NOT NULL COMMENT '카테고리명',
    UNIQUE (CATEGORY_NAME)
);

CREATE TABLE IF NOT EXISTS BOARD (
    BOARD_ID BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CREATED_DT DATETIME(6) NOT NULL,
    MODIFIED_DT DATETIME(6) NULL,
    BOARD_TITLE VARCHAR(100) NOT NULL COMMENT '게시판 제목',
    BOARD_CONTENT TEXT NOT NULL COMMENT '게시판 내용',
    BOARD_CATEGORY BIGINT NOT NULL COMMENT '게시판 카테고리',
    BOARD_USER BIGINT(20) NOT NULL COMMENT '게시판 등록자',
    BOARD_VIEW_CNT BIGINT(20) DEFAULT 0 COMMENT '조회수'
);

CREATE TABLE IF NOT EXISTS REPLY (
    REPLY_ID BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CREATED_DT DATETIME(6) NOT NULL,
    MODIFIED_DT DATETIME(6) NULL,
    REPLY_CONTENT TEXT NOT NULL COMMENT '댓글 내용',
    REPLY_USER BIGINT(20) NOT NULL COMMENT '댓글 등록자'
);
